import = [
  "~/dotfiles/.config/alacritty/flow.toml",
  "~/dotfiles/.config/alacritty/rose_pine.toml",
]

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.7
startup_mode = "Maximized"
dynamic_title = true

[scrolling]
history = 20000
